### ISSUE TITLE
not working on OSX firefox

### ISSUE THREAD

**Issue by DLewis01** [sgeto/Betty#1]
Installed under greasemonkey, but it isn't adding any links to google results

**Comment by sgeto** [comment]
Can you be more specific please. I don't have a Mac, but the script works fine on my windows box and Firefox.
When you say "isn't adding any links to google results", are you expecting it to add your desired results next to "nomal" results?
Because that's not it works. 
You would first pick from a category at the bottom (Music, Software etc.), and then type whatever you're looking for, and then press "Google Search" . That's it. The results are what you (hopefully) looking for.

I should have problably made that more clear in block. Got it?

**Comment by sgeto** [comment]
yeeeeeah....

I think we're done here.
